repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: uv run --frozen ruff format
        language: system
        types_or: [python, pyi]

      - id: ruff-check
        name: ruff check
        entry: uv run --frozen ruff check --fix
        language: system
        types_or: [python, pyi]

      - id: trailing-whitespace
        name: trim trailing whitespace
        entry: uv run --frozen trailing-whitespace-fixer
        language: system
        types: [text]

      - id: end-of-file-fixer
        name: fix end of files
        entry: uv run --frozen end-of-file-fixer
        language: system
        types: [text]

      - id: check-yaml
        name: check yaml
        entry: uv run --frozen check-yaml
        language: system
        types: [yaml]

      - id: check-toml
        name: check toml
        entry: uv run --frozen check-toml
        language: system
        types: [toml]

      - id: check-added-large-files
        name: check added large files
        entry: uv run --frozen check-added-large-files --maxkb=1024
        language: system
        pass_filenames: false

      - id: commitizen
        name: commitizen check
        entry: uv run --frozen cz check --allow-abort --commit-msg-file
        language: system
        stages: [commit-msg]
